# -*- coding: utf-8 -*-
"""rock_paper_scissor_game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jtz38X2lv1n5Cg8EQt4xhE-Zp-8yQHBh
"""

# Rock, Paper, Scissor
import random

choices = ('r','p','s')
choice = {'r': 'Rock', 'p':'Paper','s':'Scissor'}


while True:
  user_choice = input('Rock, paper or scissor? (r/p/s): ').lower()

  if user_choice not in choices:
    print('Invalid Choice')
    continue

  computer_choice = random.choice(choices)

  if user_choice == computer_choice:
    print('It is a tie')

  elif ((user_choice == 'r' and computer_choice =='s') or
  (user_choice == 'p' and computer_choice == 'r') or
    (user_choice == 's' and computer_choice =='p')):
    print('You won!')
    print(f'You chose : "{choice[user_choice]}"')
    print(f'Computer chose : "{choice[computer_choice]}"')

  else:
    print('You Lost!')
    print(f'You chose : "{choice[user_choice]}"')
    print(f'Computer chose : "{choice[computer_choice]}"')

  play_again = input('Do you want to play again ? (y/n) : ').lower()
  if play_again !='y':
    print('Thank You')
    break